version: "3.5"
services:
  db:
    image: mongo:3.6
  rabbitmq:
    image: rabbitmq:3.7-management
  document-service:
    image: com.bsamartins/falcon/document-service:latest
    build: ./document-service
    environment:
      - spring_rabbitmq_host=rabbitmq
      - spring_rabbitmq_port=5672
      - spring_data_mongodb_host=db
      - spring_data_mongodb_port=27017
    depends_on:
      - db
      - rabbitmq
  gateway:
    image: com.bsamartins/falcon/gateway:latest
    build: ./gateway
    environment:
      - spring_rabbitmq_host=rabbitmq
      - spring_rabbitmq_port=5672
      - falcon_services_documents_host=http://document-service:8080
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
      - document-service
