spring:
  cloud:
    stream:
      rabbit:
        bindings:
          documents:
            consumer:
              exchangeType: topic
          documents-created:
            producer:
              exchangeType: fanout
falcon:
  services:
    documents:
      host: http://localhost:8090
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.cloud: INFO
    com.bsamartins.falcon.gateway: DEBUG
